service:
  name: yyt-leaderboard-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: production
  region: ap-northeast-2
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:HeadObject"
      Resource:
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${env:BUCKET_NAME}"
  environment:
    REDIS_HOST: ${env:REDIS_HOST}
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}
    BUCKET_NAME: ${env:BUCKET_NAME}
    AUTH_KEY: ${env:AUTH_KEY, ""}
    BOTTOM_HALF_LAMBDA: ${self:service.name}-${self:provider.stage}-bottomHalf
    DEBUG: ${env:DEBUG, ""}
    ELAPSED: ${env:ELAPSED, "1"}

functions:
  get:
    handler: src/handler.get
    events:
      - http:
          method: get
          path: /{serviceId}/{period}
          cors: true
  me:
    handler: src/handler.me
    events:
      - http:
          method: get
          path: /{serviceId}/{period}/me
          cors: true
  top:
    handler: src/handler.top
    events:
      - http:
          method: get
          path: /{serviceId}/{period}/top
          cors: true
  around:
    handler: src/handler.around
    events:
      - http:
          method: get
          path: /{serviceId}/{period}/around
          cors: true
  scrollUp:
    handler: src/handler.scrollUp
    events:
      - http:
          method: get
          path: /{serviceId}/{period}/up
          cors: true
  scrollDown:
    handler: src/handler.scrollDown
    events:
      - http:
          method: get
          path: /{serviceId}/{period}/down
          cors: true
  put:
    handler: src/handler.put
    timeout: 6
    events:
      - http:
          method: put
          path: /{serviceId}/{period}
          cors: true
  bottomHalf:
    handler: src/handler.bottomHalf
    timeout: 900
  clear:
    handler: src/handler.clear
    events:
      - http:
          method: delete
          path: /{serviceId}/{period}
          cors: true

resources:
  Resources:
    DistBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
